package org.celtric.ai.annotations;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Indicates that the annotated code was generated by an AI assistant.
 * This annotation is for documentation purposes only and has no runtime effect.
 */
@Documented
@Retention(RetentionPolicy.SOURCE)
public @interface AIGenerated {

    /**
     * The name or identifier of the AI model/assistant that generated this code, including the version if available.
     * Examples: "GitHub Copilot", "ChatGPT-4", "Claude Opus 4.5"
     */
    String model() default "";

    /**
     * The date when the code was generated (ISO 8601 format recommended).
     * Example: "2025-12-11"
     */
    String date() default "";

    /**
     * A brief description of the prompt or intent that led to this code generation.
     */
    String prompt() default "";

    /**
     * Additional notes or context about the generated code.
     */
    String notes() default "";
}
