/**
 * AI Annotations for marking AI-generated or AI-assisted code.
 *
 * <p>This package provides a set of annotations to document the involvement of AI in code creation, modification, or
 * review. These annotations are intended for human readers only and have no runtime effect.</p>
 *
 * <h2>Available Annotations</h2>
 * <ul>
 *   <li>{@link org.celtric.ai.annotations.AIGenerated} - Code fully generated by AI</li>
 *   <li>{@link org.celtric.ai.annotations.AIAssisted} - Code written with AI collaboration</li>
 *   <li>{@link org.celtric.ai.annotations.AISuggested} - Code from accepted AI suggestions/completions</li>
 *   <li>{@link org.celtric.ai.annotations.AIReviewed} - Human code reviewed by AI</li>
 *   <li>{@link org.celtric.ai.annotations.AIRefactored} - Code refactored by AI</li>
 *   <li>{@link org.celtric.ai.annotations.HumanVerified} - AI code verified by a human</li>
 * </ul>
 *
 * <h2>Usage Examples</h2>
 * <pre>
 * {@literal @}AIGenerated(model = "GitHub Copilot (GPT-4o)", date = "2025-12-11")
 * public class GeneratedService {
 *     // ...
 * }
 *
 * {@literal @}AIAssisted(model = "Claude 3.5 Sonnet", description = "Algorithm optimization")
 * public int calculateScore() {
 *     // ...
 * }
 *
 * {@literal @}AIGenerated(model = "GPT-4 Turbo")
 * {@literal @}HumanVerified(verifier = "John Doe", date = "2025-12-11")
 * public void criticalOperation() {
 *     // ...
 * }
 * </pre>
 *
 * @since 0.1
 */
package org.celtric.ai.annotations;
